FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

MAINTAINER "Thibault Goyallon <thibault.goyallon@inria.fr>"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y --no-install-recommends update && apt-get -y --no-install-recommends upgrade && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    libatlas-base-dev \ 
    libprotobuf-dev \
    libleveldb-dev \
    libsnappy-dev \
    libhdf5-serial-dev \
    protobuf-compiler \
    libboost-all-dev \
    libgflags-dev \
    libgoogle-glog-dev \
    liblmdb-dev \
    pciutils \
    python3-setuptools \
    python3-dev \
    python3-pip \
    opencl-headers \
    ocl-icd-opencl-dev \
    libviennacl-dev \
    libcanberra-gtk-module  \
    libopencv-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libgtk2.0-dev \
    qt5-default \
    libvtk6-dev \
    zlib1g-dev


RUN apt-get -y install python3
RUN apt-get -y install pip
RUN apt-get -y install python3-tk
RUN pip3 install numpy matplotlib==3.2.1 opencv-contrib-python

CMD python3 /data/aruco.py
