FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

MAINTAINER "Thibault Goyallon <thibault.goyallon@inria.fr>"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get -y install python3
RUN apt-get -y install pip
RUN apt-get -y install python3-tk
RUN pip3 install numpy matplotlib==3.2.1
CMD python3 /data/plot.py 
